services:

  orders-api:
    build:
      context: ./application/orders-api

    container_name: acmecorp-orders-api

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql+psycopg://acme:acme@postgres:5432/acmecorp
      OTEL_SERVICE_NAME: orders-api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      INVENTORY_DELAY_SECONDS: "0"
      PAYMENTS_API_URL: http://payments-api:8001

    depends_on:
      postgres:
        condition: service_healthy
      otel-collector:
        condition: service_started
      payments-api:
        condition: service_started

  payments-api:
    build:
      context: ./application/payments-api
    container_name: acmecorp-payments-api
    ports:
      - "8001:8001"
    environment:
      OTEL_SERVICE_NAME: payments-api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      PAYMENT_FAILURE_RATE: "0"
      PAYMENTS_DELAY_SECONDS: "0"
    depends_on:
      otel-collector:
        condition: service_started
          
  postgres:
    image: postgres:16
    container_name: acmecorp-postgres
    environment:
      POSTGRES_DB: acmecorp
      POSTGRES_USER: acme
      POSTGRES_PASSWORD: acme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U acme -d acmecorp"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  otel-collector:
    image: otel/opentelemetry-collector:0.160.0
    container_name: acmecorp-otel-collector
    command:
      - "--config=/etc/otelcol/config.yaml"
    volumes:
      - ./observability/otel-collector/config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: acmecorp-jaeger
    ports:
      - "16686:16686"

  prometheus:
    image: prom/prometheus:v3.14.0
    container_name: acmecorp-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:latest
    container_name: acmecorp-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  postgres_data:
