{
 "title": "AcmeCorp - Orders API Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(acmecorp_http_requests_total[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    acmecorp_http_requests_total{\r\n      http_response_status_code=~\"500\"\r\n    }[1m]\r\n  )\r\n)\r\n/\r\nsum(\r\n  rate(\r\n    acmecorp_http_requests_total[1m]\r\n  )\r\n)\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(acmecorp_http_request_duration_milliseconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}