{
 "title": "AcmeCorp Service Health",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Orders Availability",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum(\r\n  rate(\r\n    acmecorp_http_requests_total{\r\n      service_name=\"orders-api\",\r\n      http_response_status_code!~\"5..\"\r\n    }[5m]\r\n  )\r\n)\r\n/\r\nsum(\r\n  rate(\r\n    acmecorp_http_requests_total{\r\n      service_name=\"orders-api\"\r\n    }[5m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order p95 Latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(\r\n      acmecorp_http_request_duration_milliseconds_bucket{\r\n        service_name=\"orders-api\"\r\n      }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Authorization Success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum(\r\n  rate(\r\n    acmecorp_http_requests_total{\r\n      service_name=\"payments-api\",\r\n      http_response_status_code!~\"5..\"\r\n    }[5m]\r\n  )\r\n)\r\n/\r\nsum(\r\n  rate(\r\n    acmecorp_http_requests_total{\r\n      service_name=\"payments-api\"\r\n    }[5m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}