receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: basic 
    
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Prometheus exporter configuration. 
  # OpenTelemetry's current Docker docs also uses port 8889 for Prometheus, so we will use that here.
  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    traces:
      receivers:
        - otlp

      processors:
        - batch

      exporters:
        - debug
        - otlp/jaeger

    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - debug
        - prometheus